apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: main
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`aboutme.drewspace.ro`)
      kind: Rule
      services:                       # [8]
      - kind: Service
        name: keycloak-http
        namespace: main
        port: 80
        passHostHeader: true
  tls:
    certResolver: letsencrypt