globalArguments:
  - "--global.sendanonymoususage=false"
  - "--global.checknewversion=false"
          
additionalArguments:
  - "--serversTransport.insecureSkipVerify=true"

certResolvers:
  letsencrypt:
    email: andreyindreies@gmail.com
    storage: /ssl-certs/acme-production.json
    caServer: "https://acme-v02.api.letsencrypt.org/directory"
    httpChallenge:
      entryPoint: websecure

persistence:
  storageClass: local-path
  enabled: true
  name: ssl-certs
  size: 1Gi
  path: /ssl-certs

env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        key: email
        name: credentials
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        key: apiKey
        name: credentials

logs:
  general:
    level: DEBUG

ports:
  web:
    redirectTo:
      port: websecure
      priority: 10
  websecure:
    tls:
      enabled: true
    certResolvers: cloudflare

# Disable Dashboard
ingressRoute:
  dashboard:
    enabled: false

deployment:
  enabled: true
  replicas: 1
  initContainers:
    - name: volume-permissions
      image: busybox:1.36.1
      command: 
        [
          "sh",
          "-c",
          "touch /ssl-certs/acme-production.json; chown 65532 /ssl-certs/acme-production.json; chmod -v 600 /ssl-certs/acme-production.json",
        ]
      securityContext:
        runAsNonRoot: false
        runAsGroup: 0
        runAsUser: 0
      volumeMounts:
        - name: ssl-certs
          mountPath: /ssl-certs

providers:
  kubernetesCRD:
    enabled: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true
    publishedService:
      enabled: false

rbac:
  enabled: true

service:
  enabled: true
  type: LoadBalancer
  annotations: {}
  labels: {}
  spec:
    loadBalancerIP: 192.168.1.201 # this should be an IP in the MetalLB range
  loadBalancerSourceRanges: []
  externalIPs: []

experimental:
  plugins:
    keycloakopenid:
      moduleName: "github.com/Gwojda/keycloakopenid"
      version: "v0.1.34"