additionalArguments:
  - --entrypoints.websecure.http.tls.certresolver=cloudflare
  - --entrypoints.websecure.http.tls.domains[0].main=drewspace.ro
  - --entrypoints.websecure.http.tls.domains[0].sans=*.drewspace.ro
  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
  - --certificatesresolvers.cloudflare.acme.email=andreyindreies@gmail.com
  - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
  - --certificatesresolvers.cloudflare.acme.storage=/ssl-certs/acme-production.json

# certResolvers:
#   letsencrypt:
    # email: andreyindreies@gmail.com
    # storage: /ssl-certs/acme-production.json
    # caServer: "https://acme-v02.api.letsencrypt.org/directory"
    # httpChallenge:
    #   entryPoint: traefik

# Persistent Storage
persistence:
  storageClass: local-path
  enabled: true
  name: ssl-certs
  size: 1Gi
  path: /ssl-certs

env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        key: email
        name: credentials
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        key: apiKey
        name: credentials

logs:
  general:
    level: DEBUG

ports:
  web:
    redirectTo:
      port: websecure
  websecure:
    tls:
      enabled: true
    certResolvers: cloudflare

# Disable Dashboard
ingressRoute:
  dashboard:
    enabled: true
    insecure: true

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:1.36.1
      command: 
        [
          "sh",
          "-c",
          "touch /ssl-certs/acme-production.json; chown 65532 /ssl-certs/acme-production.json; chmod -v 600 /ssl-certs/acme-production.json",
        ]
      securityContext:
        runAsNonRoot: false
        runAsGroup: 0
        runAsUser: 0
      volumeMounts:
        - name: ssl-certs
          mountPath: /ssl-certs

# Set Traefik as your default Ingress Controller, according to Kubernetes 1.19+ changes.
ingressClass:
  enabled: true
  isDefaultClass: true