apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-http
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}