lapiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-http
  {{- with .Values.service.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.service.labels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: http
spec:
  type: ClusterIP
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  sessionAffinityConfig:
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.service.httpsPort }}
      targetPort: https
      nodePort: {{ .Values.service.httpsNodePort }}
      protocol: TCP
    - name: http-management
      port: {{ .Values.service.httpManagementPort }}
      targetPort: http-management
      nodePort: {{ .Values.service.httpManagementNodePort }}
      protocol: TCP
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}