apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: imap
  namespace: main
spec:
  entryPoints:
    - imap
  routes:
    - match: HostSNI(`imap.drewspace.ro`)
      priority: 10
      services:
      - name: imap
        weight: 10 
        namespace: main
        port: app
  tls:
    certResolver: letsencrypt
    domains:
      - main: drewspace.ro
        sans:
          - "imap.drewspace.ro"
---
apiVersion: v1
kind: Service
metadata:
  name: imap
  namespace: main
spec:
  ports:
  - name: app
    port: 993
    protocol: TCP
    targetPort: app
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: imap
  namespace: main
subsets:
- addresses:
  - ip: 192.168.1.144
  ports:
  - name: app
    port: 143
    protocol: TCP