# IngressRouteTCP definition for Traefik
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: mail
  namespace: main
spec:
  entryPoints:
    - smtp
    - smtp-tls
  routes:
    - match: HostSNI(`mail.drewspace.ro`)
      priority: 10
      services:
      - name: mail
        weight: 10 
        namespace: main
        port: app
  tls:
    certResolver: letsencrypt
    passthrough: false
    domains:
      - main: drewspace.ro
        sans:
          - "mail.drewspace.ro"
---
# Service definition
apiVersion: v1
kind: Service
metadata:
  name: mail
  namespace: main
spec:
  ports:
  - name: app
    port: 25
    protocol: TCP
    targetPort: app
  type: ClusterIP
---
# Endpoints definition
apiVersion: v1
kind: Endpoints
metadata:
  name: mail
  namespace: main
subsets:
- addresses:
  - ip: 192.168.1.144
  ports:
  - name: app
    port: 25
    protocol: TCP
