name: Build and Push Docker Image to GitHub Container Registry

on:
  # Trigger the workflow on push to the main branch
  push:
    branches:
      - main
    paths:
      - "docker/**"
    

  # Allow manual triggers from the GitHub Actions dashboard
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          # Build the Docker image using the Dockerfile in the specified directory
          docker build -t ghcr.io/${{ github.repository }}/my-postgres-image:latest -f ./docker/Dockerfile ./docker

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/my-postgres-image:latest
